### DISCUSSION TITLE
分享我的 trime 主题，优化了自带主题的一些小问题

### DISCUSSION THREAD

**Discussion by chwt163** [osfans/android-rime#1425] [Show and tell | 展示]
[mytrime](https://github.com/chwt163/mytrime)

1、大按钮和小按钮两个主题，各有深色和浅色两种颜色。
2、回车键左侧的是液体键盘，当打字出现候选字的时候，会变成显示更多候选的按键。可以把每页显示候选词的数量设定为 99，使用效果更好。
3、主键盘的 axcv 键，以及数字键盘的 +-*/ 键，长按功能分别是全选、剪切、复制、粘贴。为了保持界面的简洁清爽，只在粘贴键上显示五角星的图标。
4、优化了符号键盘、表情键盘的很多小细节，使用体验更好。
5、切换至数字键盘，就是 ascii 模式，如果需要原版那种模式，把数字键盘 “number:” 那一段里的（第494行）的 “reset_ascii_mode: true” 改为 “reset_ascii_mode: false” 即可。
6、点击符号按钮，中文模式时打开的就是中文符号键盘，英文模式时打开的就是英文符号键盘。
还有其他细节。。。

增加了彩色：
![1](https://github.com/osfans/trime/assets/70951194/1df818b9-00e6-4fdc-833c-5e3d8701f69f)

小按钮主题：

![104](https://github.com/osfans/trime/assets/70951194/8701ef3e-f1dd-423a-b6b1-d3a570f2dd00)
![101](https://github.com/osfans/trime/assets/70951194/6c01a0ae-5f7e-4c10-9bc6-54473a12c0b5)
![102](https://github.com/osfans/trime/assets/70951194/749de939-0209-4bab-ba15-a53012b84c81)
![103](https://github.com/osfans/trime/assets/70951194/176d4fca-73e8-4003-8d29-d4953007f33f)

大按钮主题：
![204](https://github.com/osfans/trime/assets/70951194/04bb36a2-9ee9-4d16-80e8-a4ad8164e79c)
![201](https://github.com/osfans/trime/assets/70951194/2d5a1a07-c2a1-4d3d-8fdf-90d933e9bf57)
![202](https://github.com/osfans/trime/assets/70951194/4fe70acd-070f-449a-abdb-7fc8c6dadd60)
![203](https://github.com/osfans/trime/assets/70951194/acab38b5-1f32-44dd-beb1-883ce2fd91e4)

**Comment by wwxiaoqi** [comment]
我尝试使用 3.2.18 和 nightly-5，可是尝试在调节键盘高度相关选项：  keyboard_heigh、tround_corner、height 都不起作用。

**Comment by chwt163** [comment]
> 我尝试使用 3.2.18 和 nightly-5，可是尝试在调节键盘高度相关选项： keyboard_heigh、tround_corner、height 都不起作用。

是我这个主题吗？
keyboard_height，我这里可以哦，3.2.18

**Comment by jcleng** [comment]
感谢分享, 已经使用上,很棒👍

**Comment by tup2339** [comment]
挺好的，再问一下，想调整键位是不是只要在这一个地方剪切就行了？
![20240626115620](https://github.com/osfans/trime/assets/39553367/52297d5a-23c8-425b-9172-b84c13c9a31d)

**Comment by linzianxyz** [comment]
两个想法。
1如何切换中英文状态？
方案设置了反查，一般`引导。您的主题如何打出？

**Comment by chwt163** [comment]
> 挺好的，再问一下，想调整键位是不是只要在这一个地方剪切就行了？ ![20240626115620](https://private-user-images.githubusercontent.com/39553367/343002392-52297d5a-23c8-425b-9172-b84c13c9a31d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTEzMjEsIm5iZiI6MTcxOTQ1MTAyMSwicGF0aCI6Ii8zOTU1MzM2Ny8zNDMwMDIzOTItNTIyOTdkNWEtMjNjOC00MjViLTkxNzItYjg0YzEzYzlhMzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDAxMTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YjFmN2JmY2QxYjczNTdkMzljZjBiZjE3OTkyNjEyMThhZTVhNGZlYmI4M2MxNjczNDdiYmNlOTAzMzM2NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T7NaIm7ITxRdL_62RSez4xjgbadQPgCUh7XKYJ-5DQc)

是的，这里有详细教程：
[trime主题详解](https://github.com/osfans/trime/wiki/trime.yaml-%E8%A9%B3%E8%A7%A3)

**Comment by chwt163** [comment]
> 两个想法。 1如何切换中英文状态？ 方案设置了反查，一般`引导。您的主题如何打出？

通常输入方案自带的工具栏按钮，已经有中英切换的功能了吧？你也可以自己添加到键盘里面去。
反查的功能，我倒是没有用过，你挑一个不需要的长按符号键，把它替换成`应该就可以了。

**Comment by linzianxyz** [comment]
> > 两个想法。 1如何切换中英文状态？ 方案设置了反查，一般`引导。您的主题如何打出？
> 
> 通常输入方案自带的工具栏按钮，已经有中英切换的功能了吧？你也可以自己添加到键盘里面去。 反查的功能，我倒是没有用过，你挑一个不需要的长按符号键，把它替换成`应该就可以了。
工具栏又不可能一直开着，占用空间。如同电脑一样也不可能开着的呀。

**Comment by linzianxyz** [comment]
> > 两个想法。 1如何切换中英文状态？ 方案设置了反查，一般`引导。您的主题如何打出？
> 
> 通常输入方案自带的工具栏按钮，已经有中英切换的功能了吧？你也可以自己添加到键盘里面去。 反查的功能，我倒是没有用过，你挑一个不需要的长按符号键，把它替换成`应该就可以了。
工具栏又不可能一直开着，占用空间。如同电脑一样也不可能开着的呀。

**Comment by chwt163** [comment]
![Screenshot_20240627_175016_info plateaukao einkbro_edit_933113409934690](https://github.com/osfans/trime/assets/70951194/6e9bd16e-c5bf-4147-a7a5-7196cd71ec65)
这里不是一直都在吗？

**Comment by linzianxyz** [comment]
![IMG_20240629_094908](https://github.com/osfans/trime/assets/15376679/2451a43d-d3cb-43fd-b615-6daa5335d6c8)
为啥我的界面长这样？

**Comment by chwt163** [comment]
>  为啥我的界面长这样？

候选栏的选项按钮是由输入方案来定义的。

把以下代码命名为 xxx.custom.yaml，放在 trime 的配置文件夹，xxx根据你的输入法方案名称来写，比如我的是自然码双拼，就是double_pinyin.custom.yaml。
按钮的宽度，可以通过单引号里的空格来调节。
有的选项并不是所有输入方案都有用，可以添加#号把它注释掉。

```
# Rime schema
# encoding: utf-8
patch:
  schema:
    name: 双拼
  switches:
    - name: ascii_mode
      states: [ '中文', ' ᴀʙᴄ ' ]
      reset: 0
    - name: emoji
      states: [ ' ⋯ ', ' ☻ ' ]
      reset: 0
#    - name: traditionalization
#      states: [ '简', '繁' ]
#      reset: 0
    - name: full_shape
      states: [ '  ◗  ','  ⬥  ' ]
      reset: 0
    - name: ascii_punct
      states: ['  ੦  ','  ◍  ']
      reset: 0
    - options: [_key_paste_clip]
      states: [" ☆ "]
#    - options: [_key_Theme_settings]
#      states: [" ◲ "]
    - options: [_key_Menu]
      states: ["  ⁝  "]
    - options: [_key_Hide]
      states: [" ▾ "]  
      #states: ["⌵"]
```
