### ISSUE TITLE
[bug] Including the character (U+0027, APOSTROPHE) in "speller/alphabet" changes the keyboard layout for the schema

### ISSUE THREAD

**Issue by rodrigo-morales-1** [osfans/android-rime#1415]
- [Brief description of the bug](#org8903d86)
- [Experiment](#orgfb1edb1)
- [System information](#org5b01ed4)
- [Personal thoughts](#org33dcce2)
- [Additional information](#orgdbe35fb)

I'm not a Chinese native speaker, but I'm learning Chinese and I like using RIME.

<a id="org8903d86"></a>

# Brief description of the bug

When the key `speller/alphabet` in an schema contains the character `'` (U+0027, APOSTROPHE), the keyboard layout is changed for that specific schema.

The screenshot below shows the keyboard layout that is used for a schema that **doesn't include** the character `'` (U+0027, APOSTROPHE) in `speller/alphabet`.

![image](https://github.com/osfans/trime/assets/74389646/dbed7efd-3a00-4b67-8310-1211406739b2)

The screenshot below shows the keyboard layout that is used for a schema that **includes** the character `'` (U+0027, APOSTROPHE) in `speller/alphabet`.

![image](https://github.com/osfans/trime/assets/74389646/632768bb-f2bd-4529-8a2f-7ade0f6ecfb2)

See section "Experiment" for instructions on how to reproduce this issue.

<a id="orgfb1edb1"></a>

# Experiment

I downloaded `com.osfans.trime-v3.2.18-0-gc10e2e84-arm64-v8a-release.apk` from <https://github.com/osfans/trime/releases/tag/v3.2.18> and installed it on my Android device.

I removed all files in `/storage/emulated/0/rime` to avoid other files interfering with this experiment.

```sh
ssh phone-samsung 'rm -rf /storage/emulated/0/rime && mkdir /storage/emulated/0/rime'
```

I cloned `rime-prelude` in my desktop computer.

```sh
rm -rf /tmp/rime \
  && mkdir /tmp/rime \
  && cd /tmp/rime \
  && git clone --branch master --depth 1 'https://github.com/rime/rime-prelude'
```

I created some simple schemas and dictionaries to demostrate this bug.

`/tmp/rime/foo.dict.yaml` (see code block below)

```yaml
---
name: foo
version: 1
sort: original
...
111	a
222	ab
333	abc
```

`/tmp/rime/foo.schema.yaml` (see code block below)

```yaml
schema:
  schema_id: foo
  name: Schema foo
  version: 1

engine:
  processors:
  - ascii_composer
  - selector
  - key_binder
  - speller
  - selector
  - navigator
  - express_editor
  segmentors:
  - ascii_segmentor
  - abc_segmentor
  - punct_segmentor
  - fallback_segmentor
  translators:
  - table_translator

speller:
  alphabet: "abc"
  auto_select: false

translator:
  dictionary: foo
  enable_user_dict: false

key_binder:
  import_preset: default
```

`/tmp/rime/bar.schema.yaml` (see code block below)

```yaml
---
name: bar
version: 1
sort: original
...
111111	a
222222	ab
333333	abc
```

`/tmp/rime/bar.schema.yaml` (see code block below)

```yaml
schema:
  schema_id: bar
  name: Schema bar
  version: 1

engine:
  processors:
  - ascii_composer
  - selector
  - key_binder
  - speller
  - selector
  - navigator
  - express_editor
  segmentors:
  - ascii_segmentor
  - abc_segmentor
  - punct_segmentor
  - fallback_segmentor
  translators:
  - table_translator

speller:
  alphabet: "abc"
  auto_select: false

translator:
  dictionary: bar
  enable_user_dict: false

key_binder:
  import_preset: default
```

`/tmp/rime/baz.dict.yaml` (see code block below)

```yaml
---
name: baz
version: 1
sort: original
...
111111111	a
222222222	ab
333333333	abc
```

`/tmp/rime/baz.schema.yaml` (see code block below)

```yaml
schema:
  schema_id: baz
  name: Schema baz
  version: 1

engine:
  processors:
  - ascii_composer
  - selector
  - key_binder
  - speller
  - selector
  - navigator
  - express_editor
  segmentors:
  - ascii_segmentor
  - abc_segmentor
  - punct_segmentor
  - fallback_segmentor
  translators:
  - table_translator

speller:
  alphabet: "abc'"
  auto_select: false

translator:
  dictionary: baz
  enable_user_dict: false

key_binder:
  import_preset: default
```

`/tmp/rime/default.custom.yaml` (see code block below)

```text
patch:
  schema_list:
  - schema: foo
  - schema: bar
  - schema: baz
```

I used the folowing command to transfer the `*.yaml` files from my desktop computer to my Android device into the directory that Trime searches files.

```sh
rsync -Pvv \
  /tmp/rime/rime-prelude/default.yaml \
  /tmp/rime/rime-prelude/key_bindings.yaml \
  /tmp/rime/rime-prelude/punctuation.yaml \
  /tmp/rime/rime-prelude/symbols.yaml \
  /tmp/rime/foo.schema.yaml \
  /tmp/rime/foo.dict.yaml \
  /tmp/rime/bar.schema.yaml \
  /tmp/rime/bar.dict.yaml \
  /tmp/rime/baz.schema.yaml \
  /tmp/rime/baz.dict.yaml \
  /tmp/rime/default.custom.yaml \
  phone-samsung:/storage/emulated/0/rime
```

I enabled the schemas in Trime. After the message `Deploying...` disappeared, I opened an application to input text.

The following screenshot shows the keyboard layout when using `Schema foo`.

![image](https://github.com/osfans/trime/assets/74389646/9e1d848f-c972-4365-b2b2-7d1b885c2e6d)

The following screenshot shows the keyboard layout when using `Schema bar`.

![image](https://github.com/osfans/trime/assets/74389646/210999e9-9d65-4016-a18c-fb78242c45d0)

The following screenshot shows the keyboard layout when using `Schema baz`.

![image](https://github.com/osfans/trime/assets/74389646/2650de13-d111-456c-bc2d-2f4aec9693e1)

As you can see above, `Schema foo` and `Schema bar` use the same keyboard layout. However, `Schema baz` use a different keyboard layout.

<a id="org5b01ed4"></a>

# System information

I used the latest release as of time of writing: I installed `com.osfans.trime-v3.2.18-0-gc10e2e84-arm64-v8a-release.apk` which I downloaded from <https://github.com/osfans/trime/releases/tag/v3.2.18>.

<a id="org33dcce2"></a>

# Personal thoughts

I believe this is a bug because the value of `speller/alphabet` shouldn't affect the keyboard layout.

In my opinion, having two different keyboard layouts for different input methods is not convenient because the user has to remember the position of the keys for two different keyboard layouts.

When I use RIME in my desktop computer, I use the same keyboard for all input methods.

<a id="orgdbe35fb"></a>

# Additional information

I installed version 3.2.17 `com.osfans.trime-nightly-0-g98e201b9-arm64-v8a-release.apk` which I downloaded from <https://github.com/osfans/trime/releases/tag/v3.2.17> and I could reproduce the same issue.

I installed version 3.2.16 (`trime-3.2.16-arm64-v8a-debug.apk` which I downloaded from <https://github.com/osfans/trime/releases/tag/v3.2.16>) and I couldn't reproduce this issue.

Therefore, I believe that version 3.2.17 introduced some changes that caused this bug.

**Comment by WhiredPlanck** [comment]
Hi, @rodrigomorales1 ~! Thanks for your feedback. Currently Trime will select an appropriate keyboard layout smartly according to `spller/alphabet` filed.

**Comment by rodrigo-morales-1** [comment]
@WhiredPlanck I didn't know that. Thanks!

I have a question: Is it possible to force Trime use a specific keyboard layout for a given schema? I'm asking because I wish `Schema baz` used this keyboard layout:

![image](https://github.com/osfans/trime/assets/74389646/dbed7efd-3a00-4b67-8310-1211406739b2)

instead of this keyboard layout:

![image](https://github.com/osfans/trime/assets/74389646/632768bb-f2bd-4529-8a2f-7ade0f6ecfb2)

**Comment by WhiredPlanck** [comment]
> I have a question: Is it possible to force Trime use a specific keyboard layout for a given schema?

Of course, but you need to make the keyboard id (the key of the yaml config map) as same as the schema id.

**Comment by rodrigo-morales-1** [comment]
> Of course, but you need to make the keyboard id (the key of the yaml config map) as same as the schema id.

@WhiredPlanck What is the "yaml config map"?

**Comment by WhiredPlanck** [comment]
> > Of course, but you need to make the keyboard id (the key of the yaml config map) as same as the schema id.
> 
> @WhiredPlanck What is the "yaml config map"?

Look at this screenshoot, this is a config of the `default` keyboard while `default` is the `key` of this map structure config segment, i.e. the keyboard id. Currently every theme config file contains `preset_keyboards` to store a set of keyboard definitions.

![Screenshot_2024-07-23-19-15-38-310_bin mt plus-edit](https://github.com/user-attachments/assets/9214f121-eba2-4977-bb60-bbd3b7fe9b66)

**Comment by rodrigo-morales-1** [comment]
After some hours of trial and error, I was able to change the keyboard layout for a specific schema. I'll explain how I did it just in case someone wants to do the same in the future. @WhiredPlanck please feel free to correct my explanation if you find some mistakes or you are aware of better ways to get the same behavior.

**TL: DR:** Insert the code block below to `trime.custom.yaml` and copy that file to the directory where you have installed the `*.schema.yaml` and `*.dict.yaml` files (in my phone, I copied it to `/sdcard/rime/trime.custom.yaml`)

```
patch:
  "preset_keyboards/baz":
    __include: trime.yaml:preset_keyboards/qwerty
```

**Detailed steps:** I used the command shown below to download a community schema. I chose rime-pinyin-simp because it doesn't have dependencies and to make this explanation simpler.

```sh
rm -rf /tmp/rime \
  && mkdir /tmp/rime \
  && cd /tmp/rime \
  && git clone --branch master --depth 1 'https://github.com/rime/rime-pinyin-simp'
```

I created the files shown below:

`/tmp/rime/baz.schema.yaml`:

```text
schema:
  schema_id: baz
  name: Schema baz
  version: 1

engine:
  processors:
  - ascii_composer
  - selector
  - key_binder
  - speller
  - selector
  - navigator
  - express_editor
  segmentors:
  - ascii_segmentor
  - abc_segmentor
  - punct_segmentor
  - fallback_segmentor
  translators:
  - table_translator

speller:
  alphabet: "iou'"
  auto_select: false

translator:
  dictionary: baz
  enable_user_dict: false

key_binder:
  import_preset: default
```

`/tmp/rime/baz.dict.yaml`:

```text
---
name: baz
version: 1
sort: original
...
111	i
222	io
333	iou
```

`/tmp/rime/trime.custom.yaml`:

```text
patch:
  "preset_keyboards/baz":
    __include: trime.yaml:preset_keyboards/qwerty
```

I used the command shown below to remove all files in the directory `/sdcard/rime`. I did this to make sure that there was no other file that would interfer with the default behavior.

```sh
ssh samsung-galaxy-a02s 'rm -rf /sdcard/rime ; mkdir /sdcard/rime'
```

I transferred the files from my desktop computer to my phone using the command shown below:

```sh
rsync -Psavv \
      /tmp/default.custom.yaml \
      /tmp/rime/rime-pinyin-simp/pinyin_simp.dict.yaml \
      /tmp/rime/rime-pinyin-simp/pinyin_simp.schema.yaml \
      /tmp/rime/baz.dict.yaml \
      /tmp/rime/baz.schema.yaml \
      /tmp/rime/trime.custom.yaml \
      samsung-galaxy-a02s:/sdcard/rime
```

At this point, the directory looked like this:

```text
$ ssh samsung-galaxy-a02s find /sdcard/rime | tree --fromfile -a --noreport
.
└── sdcard
    └── rime
        ├── baz.dict.yaml
        ├── baz.schema.yaml
        ├── default.custom.yaml
        ├── pinyin_simp.dict.yaml
        ├── pinyin_simp.schema.yaml
        └── trime.custom.yaml
```

I opened Trime. I pressed on "Schemata" in the main menu. I pressed on the button "ENABLE SCHEMATA" in the bottom right corner. I selected "Schema baz" and "" in the selection list and I pressed the button "OK" in the bottom right corner, the message "Deploying&#x2026;" was shown. After the message "Deploying&#x2026;" disappeared, the directory looked like this:

```text
$ ssh samsung-galaxy-a02s find /sdcard/rime | tree --fromfile -a --noreport
.
└── sdcard
    └── rime
        ├── baz.dict.yaml
        ├── baz.schema.yaml
        ├── build
        │   ├── baz.prism.bin
        │   ├── baz.reverse.bin
        │   ├── baz.schema.yaml
        │   ├── baz.table.bin
        │   ├── default.yaml
        │   ├── pinyin_simp.prism.bin
        │   ├── pinyin_simp.reverse.bin
        │   ├── pinyin_simp.schema.yaml
        │   └── pinyin_simp.table.bin
        ├── default.custom.yaml
        ├── installation.yaml
        ├── opencc
        ├── pinyin_simp.dict.yaml
        ├── pinyin_simp.schema.yaml
        ├── trime.custom.yaml
        └── user.yaml
```

I closed Trime. Upon closing Trime, I noticed that the file `/sdcard/rime/build/trime.yaml` was created. The code block below shows the files in `/sdcard/rime` after having closed Trime. Note: I can't absolutely confirm this but it seems that it is necessary that `trime.yaml` gets created to consistently apply the rules in `trime.custom.yaml`.

```text
$ ssh samsung-galaxy-a02s find /sdcard/rime | tree --fromfile -a --noreport
.
└── sdcard
    └── rime
        ├── baz.dict.yaml
        ├── baz.schema.yaml
        ├── build
        │   ├── baz.prism.bin
        │   ├── baz.reverse.bin
        │   ├── baz.schema.yaml
        │   ├── baz.table.bin
        │   ├── default.yaml
        │   ├── pinyin_simp.prism.bin
        │   ├── pinyin_simp.reverse.bin
        │   ├── pinyin_simp.schema.yaml
        │   ├── pinyin_simp.table.bin
        │   └── trime.yaml
        ├── default.custom.yaml
        ├── installation.yaml
        ├── opencc
        ├── pinyin_simp.dict.yaml
        ├── pinyin_simp.schema.yaml
        ├── trime.custom.yaml
        └── user.yaml
```

I used the command shown below to see whether the file `/sdcard/rime/build/trime.yaml` defined rules for the schema `baz` and it did:

```sh
ssh samsung-galaxy-a02s cat /sdcard/rime/build/trime.yaml | grep -A 17 'baz' ; echo Exit code: $?
```

      baz:
        ascii_mode: 0
        author: "osfans <waxaca@163.com>"
        columns: 10
        height: 55
        key_hint_offset_x: 0
        key_hint_offset_y: 0
        key_press_offset_x: 2
        key_press_offset_y: 2
        key_symbol_offset_x: 0
        key_symbol_offset_y: 0
        key_text_offset_x: 0
        key_text_offset_y: 0
        keys: [{click: q, long_click: "!", swipe_up: 1}, {click: w, long_click: "@", swipe_up: 2}, {click: e, long_click: "#", swipe_up: 3}, {click: r, long_click: "$", swipe_up: 4}, {click: t, long_click: "%", swipe_up: 5}, {click: y, long_click: "^", swipe_up: 6}, {click: u, long_click: "&", swipe_up: 7}, {click: i, long_click: "*", swipe_up: 8}, {click: o, long_click: "(){Left}", swipe_up: 9}, {click: p, long_click: Hide, swipe_up: 0}, {width: 5}, {click: a, long_click: select_all, swipe_down: Down, swipe_left: Left, swipe_right: Right, swipe_up: Up}, {click: s, long_click: "~", swipe_down: Page_Down, swipe_left: Home, swipe_right: End, swipe_up: Page_Up}, {click: d, long_click: "-", swipe_down: _}, {click: f, long_click: "+", swipe_down: "="}, {click: g, long_click: "\\", swipe_down: "|"}, {click: h, long_click: "[]{Left}", swipe_left: "[", swipe_right: "]"}, {click: j, long_click: "{}{Left}", swipe_left: "{", swipe_right: "}"}, {click: k, long_click: ":"}, {click: l, long_click: ";"}, {width: 5}, {click: Shift_L, send_bindings: false, width: 15}, {click: z, long_click: "`"}, {click: x, long_click: cut}, {click: c, long_click: copy}, {click: v, long_click: paste}, {click: b, long_click: Time, swipe_up: Date}, {click: n, long_click: "\""}, {click: m, long_click: "'"}, {click: BackSpace, swipe_left: Escape, width: 15}, {click: Mode_switch, long_click: Menu, width: 15}, {click: Keyboard_symbols, long_click: Keyboard_number}, {click: ",", long_click: "<"}, {click: space, width: 30}, {click: ., long_click: ">"}, {click: "/", long_click: "?"}, {click: Return, composing: Return1, long_click: CommitComment, width: 15}]
        lock: true
        name: "預設26鍵"
        width: 10
      bopomofo:
    Exit code: 0

I opened "Simple Text Editor" (a simple application that allow typing) in order to show my phone's keyboard. When the keyboard was shown, the schema "Schema baz" with the `default` keyboard layout was used (see first screenshot below) (this is not what I wanted). I then switched to the schema "袖珍简化字拼音" and the keyboard `qwerty` was used (see second screenshot below.) Then, I switched back to "Schema baz" and the keyboard layout `qwerty` was used (the same keyboard used by "袖珍简化字拼音") (see third screenshot below).

First screenshot:
![image](https://github.com/user-attachments/assets/e7695044-04fd-40a2-956b-da877a30494c)

Second screenshot:
![image](https://github.com/user-attachments/assets/c51d64e7-82e7-48bf-987c-a97f9c801271)

Third screenshot:
![image](https://github.com/user-attachments/assets/1d707f2c-8188-411f-bb9f-ea2f141018a5)

**Comment by rodrigo-morales-1** [comment]
For reference: In version 3.3.2, I can switch to the keyboard layout `qwerty` by creating `trime.custom.yaml` in the file `/sdcard/rime` in my Android device.

```
patch:
    "preset_keyboards/spanish":
        __include: trime.yaml:preset_keyboards/qwerty
    "preset_keyboards/wubi86":
        __include: trime.yaml:preset_keyboards/qwerty
    "preset_keyboards/wubi86_8105":
        __include: trime.yaml:preset_keyboards/qwerty
    "preset_keyboards/double_pinyin_flypy":
        __include: trime.yaml:preset_keyboards/qwerty
    "preset_keyboards/pinyin_simp":
        __include: trime.yaml:preset_keyboards/qwerty
```
