### ISSUE TITLE
Add shortcut for inserting current timestamp in ISO 8601 format (e.g. 2025-06-02T11:10:56+12:00)

### ISSUE THREAD

**Issue by rodrigo-morales-1** [osfans/android-rime#1661]
### 摘要 / Summary

I think it would be convenient for some users if Trime had a shortcut for inserting the current timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. For those that are not familiar with the format ISO 8601, here are some examples of timestamps in format ISO8601:

```text
2025-06-01T11:10:56−12:00
2025-06-01T23:10:56+00:00
2025-06-02T11:10:56+12:00
```

I feel a good choice would be to use `swipe_down` in letter `b` to insert current timestamp in ISO8601, because, in version 3.3.4, `b` is used to insert the current date (`swipe_up`) and current time (`long_click`).

<https://github.com/osfans/trime/blob/5ec15ed0d8deba73efde2c9db25785ddc0d6023e/app/src/main/assets/shared/trime.yaml#L1209>

Here's the definition of `Time` and `Date`:

<https://github.com/osfans/trime/blob/be66f30faf26d42ec69c3ce12e25615b43ca32ee/app/src/main/assets/shared/trime.yaml#L958>

<https://github.com/osfans/trime/blob/be66f30faf26d42ec69c3ce12e25615b43ca32ee/app/src/main/assets/shared/trime.yaml#L956>

### 替代方案 / Alternative Solution

In v3.3.4, I can insert a timestamp in ISO 8601 by following these steps:

1.  Swiping up on the key `b`
2.  Type `T`
3.  Long clicking on the key `b`
4.  Type `-0500`

If Trime had a shortcut for inserting the current timestamp in ISO8601. Those four steps would be reduced to a single step which would be very convenient for me.

### 附加信息 / Additional Context

The code block below shows how to print the current date in ISO 8601 using Python.

```python
import time
print(time.strftime("%Y-%m-%dT%H:%M:%S%z"))
```

    2025-06-01T18:18:30-0500

The example below shows how to print the current date in ISO 8601 using bash.

```sh
date "+%Y-%m-%dT%H:%M:%S%z"
```

    2025-06-01T18:19:35-0500

### 系统版本 / OS Version

Android version 13

### 应用版本 / App Version

Version 3.3.2

### 构建信息 / Build Information

Builder: Release CI
Git Repo: https://github.com/osfans/trime
Build Git Hash: 359d86ac89894912abe44704670477c4fb534d87
Build Time: 1 Jan 2025 4:50:43 am

**Comment by rodrigo-morales-1** [comment]
I managed to accomplish this behavior by modifying the `qwerty` keyboard as shown below.

`trime.custom.yaml`

```
patch:
  "preset_keys/MyDateAndTimeISO8601": {label: 日期, command: date, option: "yyyy-MM-dd'T'HH:mm:ssZ"}
  "preset_keyboards/wubi86":
    __include: my_keyboards.yaml:my_qwerty
  "preset_keyboards/spanish":
    __include: my_keyboards.yaml:my_qwerty
  "preset_keyboards/wubi86":
    __include: my_keyboards.yaml:my_qwerty
  "preset_keyboards/wubi86_8105":
    __include: my_keyboards.yaml:my_qwerty
  "preset_keyboards/double_pinyin_flypy":
    __include: my_keyboards.yaml:my_qwerty
  "preset_keyboards/pinyin_simp":
    __include: my_keyboards.yaml:my_qwerty
```

`my_keyboards.yaml`

```
my_qwerty:
    # based on https://github.com/osfans/trime/blob/be66f30faf26d42ec69c3ce12e25615b43ca32ee/app/src/main/assets/shared/trime.yaml#L1166
    name: 預設26鍵
    author: "osfans <waxaca@163.com>"
    ascii_mode: 0
    columns: 10 #鍵盤列數，超過則自動換行，默認30列
    width: 10
    height: 55
    lock: true
    key_symbol_offset_x: 0
    key_symbol_offset_y: 0
    key_text_offset_x: 0
    key_text_offset_y: 0
    key_hint_offset_x: 0
    key_hint_offset_y: 0
    key_press_offset_x: 2
    key_press_offset_y: 2
    keys:
    - {click: 'q', long_click: '!', swipe_up: 1}
    - {click: 'w', long_click: '@', swipe_up: 2}
    - {click: 'e', long_click: '#', swipe_up: 3}
    - {click: 'r', long_click: '$', swipe_up: 4}
    - {click: 't', long_click: '%', swipe_up: 5}
    - {click: 'y', long_click: '^', swipe_up: 6}
    - {click: 'u', long_click: '&', swipe_up: 7}
    - {click: 'i', long_click: '*', swipe_up: 8}
    - {click: 'o', long_click: '(){Left}', swipe_up: 9}
    - {click: 'p', long_click: 'Hide', swipe_up: 0}
    - {width: 5}
    - {click: 'a', long_click: select_all, swipe_left: Left, swipe_right: Right, swipe_up: Up, swipe_down: Down}
    - {click: 's', long_click: '~', swipe_left: Home, swipe_right: End, swipe_up: Page_Up, swipe_down: Page_Down}
    - {click: 'd', long_click: '-', swipe_down: '_'}
    - {click: 'f', long_click: '+', swipe_down: '='}
    - {click: 'g', long_click: '\', swipe_down: '|'}
    - {click: 'h', long_click: '[]{Left}', swipe_left: '[', swipe_right: ']'}
    - {click: 'j', long_click: '{}{Left}', swipe_left: '{', swipe_right: '}'}
    - {click: 'k', long_click: ':'}
    - {click: 'l', long_click: ';'}
    - {width: 5}
    - {click: Shift_L, send_bindings: false, width: 15}
    - {click: 'z', long_click: '`'}
    - {click: 'x', long_click: cut}
    - {click: 'c', long_click: copy}
    - {click: 'v', long_click: paste}
    - {click: 'b', long_click: Time, swipe_up: Date, swipe_down: MyDateAndTimeISO8601}
    - {click: 'n', long_click: '"'}
    - {click: 'm', long_click: "'"}
    - {click: BackSpace, swipe_left: Escape, width: 15}
    - {click: Mode_switch, long_click: Menu, width: 15}
    - {click: Keyboard_symbols, long_click: Keyboard_number}
    - {click: ',', long_click: '<'}
    - {click: space, width: 30}
    - {click: '.', long_click: '>'}
    - {click: '/', long_click: '?'}
    - {click: Return, composing: Return1, long_click: CommitComment, width: 15}
```
